call pathogen#infect()
filetype plugin on
filetype indent on
syntax on
set mouse=nicr
set number
set background=dark
set tabstop=4 shiftwidth=4 expandtab 
set completeopt=menuone,longest,preview
set cursorline
set nocursorline
nmap <F5> :w<CR>:!bash -c %:p<CR>
nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>
set scrolloff=15
set modeline
set ls=2

highlight Pmenu ctermfg=white ctermbg=black
highlight PmenuSel ctermfg=black ctermbg=white

nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>

set viminfo='10,\"100,:20,%,n~/.viminfo

"hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
"hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
"nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

